apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |

    server {
      listen 80;
      index index.php index.html;
      root /usr/share/nginx/html;

      rewrite ^/google$ http://google.com permanent;
    }