apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx2-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: nginx2-deployment
  targetCPUUtilizationPercentage: 20